-- MySQL Script generated by MySQL Workbench
-- jue 17 ene 2019 20:34:40 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdcar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdcar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcar` DEFAULT CHARACTER SET utf8 ;
USE `bdcar` ;

-- -----------------------------------------------------
-- Table `bdcar`.`seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdcar`.`seccion` ;

CREATE TABLE IF NOT EXISTS `bdcar`.`seccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_seccion` VARCHAR(255) NOT NULL,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcar`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdcar`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `bdcar`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcar`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdcar`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bdcar`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `ape1` VARCHAR(255) NOT NULL,
  `ape2` VARCHAR(255) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_alta` DATETIME NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `confirmado` TINYINT(1) NOT NULL,
  `id_tipo_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`id_tipo_usuario` ASC),
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `bdcar`.`tipo_usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcar`.`articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdcar`.`articulo` ;

CREATE TABLE IF NOT EXISTS `bdcar`.`articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `desc` VARCHAR(255) NULL,
  `fecha` DATETIME NOT NULL,
  `articulo` LONGTEXT NOT NULL,
  `etiquetas` VARCHAR(255) NULL,
  `id_seccion` INT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articulo_seccion_idx` (`id_seccion` ASC),
  INDEX `fk_articulo_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_articulo_seccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bdcar`.`seccion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_articulo_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bdcar`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcar`.`sugerencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdcar`.`sugerencia` ;

CREATE TABLE IF NOT EXISTS `bdcar`.`sugerencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `sugerencia` LONGTEXT NOT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sugerencia_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_sugerencia_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bdcar`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcar`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdcar`.`categoria` ;

CREATE TABLE IF NOT EXISTS `bdcar`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcar`.`imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdcar`.`imagen` ;

CREATE TABLE IF NOT EXISTS `bdcar`.`imagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_imagen` VARCHAR(255) NOT NULL,
  `desc` VARCHAR(255) NULL,
  `foto` VARCHAR(255) NOT NULL,
  `id_usuario` INT NULL,
  `id_categoria` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagen_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_imagen_categoria1_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_imagen_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bdcar`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_imagen_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `bdcar`.`categoria` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
